import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar/page";

const julius = localFont({ src: "./fonts/JuliusSansOne-Regular.ttf" });

export const metadata: Metadata = {
  title: "Income Management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={julius.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
