import type { Metadata } from "next";
import { Julius_Sans_One } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/page";

const julius = Julius_Sans_One({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Income Management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={julius.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
